version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python ./chatbot_test.py
          name: ChatbotTest
          
      - run:
          command: python ./hw13_test.py
          name: HW13 test

workflows:
  main:
    jobs:
      - build-and-test

